#! /bin/bash

cd /var/update-osm
wget http://download.geofabrik.de/osm/asia/indonesia.osm.bz2 -O indonesia.osm.bz2
echo "dropping building view"
psql -U aifdr -d osm -c "DROP VIEW vw_planet_osm_polygon;"
echo "Downloading indonesia osm xml file"
osm2pgsql  -U aifdr -d osm -S aifdr.style indonesia.osm.bz2
psql -U aifdr -d osm -f create_views.sql
