#! /bin/bash

echo "dropping building view"
#psql -U aifdr -h localhost -d osm -c "DROP VIEW vw_planet_osm_polygon;"
echo "Downloading indonesia osm xml file"
cd /var/update-osm
#wget http://download.geofabrik.de/osm/asia/indonesia.osm.bz2 -O indonesia.osm.bz2
osm2pgsql -d osm -S aifdr.style indonesia.osm.bz2
psql -U aifdr -h localhost -d osm -f create_views.sql
